[package]
name    = "count-of"
version = "0.1.0"
authors = ["pba"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn         = { version = "2.0.15", features = ["full"] }
quote       = "1.0.26"
Inflector   = "0.11.4"
proc-macro2 = "1.0.56"
